development:
  adapter: postgresql
  encoding: unicode
  database: demo_development
  pool: 5
  username: postgres
  password: 


  test:
  adapter: postgresql
  encoding: unicode
  database: demo_test
  pool: 5
  username: postgres
  password: 