# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea8bbf17c47cc7af7a5674e0ca41d3e3a7471b61be2107f9cc74eaef84d370cb591728da5817a511c9c19689b2313ae068412bda7f05b6ee7e1cef6eb38a79ce

test:
  secret_key_base: 7336d85fcbc9cd41440d2cdf528829201becc2c9310a69e720a243200a7097a4be7bb0b3f37b32f603cf0deb7cc18fd5f973677cf680c48529ffa4d13dc611aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
